### ISSUE TITLE
Large blueprint exception

### ISSUE THREAD

**Issue by Zimtrax** [Zimtrax/blueprint-power-consumption-calculator#1]
[This large blueprint ](https://pastebin.com/eSyS96CC)throws the following exception:
```
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at BPCC.inflate(BPCC.java:96)
        at BPCC.main(BPCC.java:54)
```

**Comment by Zimtrax** [comment]
This seems to be a limitation in the Windows CMD.
